services:
  - type: web
    name: neomonastery-production
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"